### ISSUE TITLE
[Game Memory] Enhancement: Show Linear Depth

### ISSUE THREAD

**Issue by misterperson** [TekkenOverlay/TekkenOverlay#10]
The current depthbuffer uses non-linear depth (all values are very, very close to 0 by design, and there's low contrast when visualizing it in the game memory tab).

The following HLSL snippet converts a non-linear depth to a linear value

```hlsl
// DepthBuffer is the depth buffer, Projection is the float4x4 projection matrix
float zw = DepthBuffer.Load(pixelCoord);
float linearZ = Projection._43 / (zw - Projection._33);
```

**Comment by ParkourGrip** [comment]
I don't see a problem. The game memory view is meant to be used by us developers to diagnose problems faster. It should display what is inside the actual memory to avoid confusion.
