### ISSUE TITLE
Question about frame 

### ISSUE THREAD

**Issue by Hyundai0** [TekkenOverlay/TekkenOverlay#103]
How can i find my minus frame to using game memory addresses?

**Comment by ParkourGrip** [comment]
It's not stored anywhere in memory. 
You have extract information about attackers and defenders animations. 
How long is the animation is in frames and what's the current frame of animation that both characters are in. 
After that you need to do some math to figure out how many frames quicker or slower the attacker will recover from the defender.
That's your +/- frames that Tekken Overlay calculates and displays.
