### ISSUE TITLE
About the lag fix.

### ISSUE THREAD

**Issue by UrsoManso** [TekkenOverlay/TekkenOverlay#104]
Even tho the game does feels more responsive with it enabled, I've read that it can cause issues for the opponent if they don't have it as well. Is that really a thing? I'm not using the FPS unlocker, only the the lag fix.

**Comment by KulaGGin** [comment]
It makes your game enter everything one frame earlier, and so it sends into to the opponent that you've entered your inputs 1 frame earlier. This can cause 1 frame more of rollback on the opponent's screen. This is in effect "rollback netcode" everyone was asking for.
