### ISSUE TITLE
unplayable online - communication errors

### ISSUE THREAD

**Issue by maligeez** [TekkenOverlay/TekkenOverlay#105]
doesnt work at the moment, communication errors every time

**Comment by Yudoken** [comment]
The ''Due to a connection error or abnormalities in your opponent's gameplay, the match will be cancelled'' error is quite annoying, it can happen after dozens of matches or even after just one. Would be fantastic if it's possible to get it fixed. Really bums me out playing ranked.

**Comment by KulaGGin** [comment]
> The ''Due to a connection error or abnormalities in your opponent's gameplay, the match will be cancelled'' error

What version of the overlay are you using?

**Comment by Yudoken** [comment]
> > The ''Due to a connection error or abnormalities in your opponent's gameplay, the match will be cancelled'' error
> 
> What version of the overlay are you using?

TekkenOverlay-5.10.2

**Comment by KulaGGin** [comment]
Can't reproduce. I just played for an hour straight with the same player.

Also:

> The ''Due to a connection error or abnormalities in your opponent's gameplay, the match will be cancelled'' error is quite annoying, it can happen after dozens of matches or even after just one. It often happens right before a match starts after a rematch.

This is just normal behavior for the game without the overlay.
