### ISSUE TITLE
Doesn't work with the newest version of tekken

### ISSUE THREAD

**Issue by Slevin94** [TekkenOverlay/TekkenOverlay#106]
It doesn't seem to work after the update anylonger :(

**Comment by ParkourGrip** [comment]
![image](https://user-images.githubusercontent.com/1338621/207466776-774133ee-fbd1-4073-bc37-6c20cfc2b9a5.png)
Give us a week.

**Comment by Hwhmeeee** [comment]
Me too. i cannot play without fps mod

**Comment by Slevin94** [comment]
I need the fov mod. Playing with black bars on my ultrawide monitor isn't fun after getting used to the opposite :(

**Comment by JackMcCallum** [comment]
Do not, my friends, become addicted to TekkenOverlay. It will take hold of you, and you will resent its absence!

**Comment by ParkourGrip** [comment]
![image](https://user-images.githubusercontent.com/1338621/207910650-0e30d9ce-0b55-42b3-bbc8-102c0c030ece.png)
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.0
