### ISSUE TITLE
Repeat action manager not working

### ISSUE THREAD

**Issue by GlouBoux** [TekkenOverlay/TekkenOverlay#108]
Hello,
Since last release, Repeat Action Manager does not work anymore.
Only move selected in practice are used.
I've tryed enable/disable movelist random fix : this change nothing.
Other features seems working.
Do you also encountered this trouble ?

**Comment by KulaGGin** [comment]
Addresses weren't updated for the new 5.10 patch for the Repeat Action Manager module. I updated them and made a new release: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.2

Try it and see if it works.

**Comment by GlouBoux** [comment]
It works now.
Thanks you :)
