### ISSUE TITLE
Unable to find Ping show option

### ISSUE THREAD

**Issue by JustinHit** [TekkenOverlay/TekkenOverlay#11]
Where can I find the ping option where it shows the delay in ms?

**Comment by JackMcCallum** [comment]
It doesnt

**Comment by JustinHit** [comment]
Oh, is there a possibility to add a ping option in the future or is that not realistic?

**Comment by JackMcCallum** [comment]
There is a frame delay in there, thats the most accurate it will probably get

**Comment by JustinHit** [comment]
Frame delay and ping are two different things though.

**Comment by ParkourGrip** [comment]
We don't yet support ping display in ms. We do plan to try to make a proper quake style lagommeter later dough.

**Comment by ParkourGrip** [comment]
From version `4.01.1` this is supported.
