### ISSUE TITLE
Game crashes as soon as I open the menu in Pratice mode

### ISSUE THREAD

**Issue by Shayoden** [TekkenOverlay/TekkenOverlay#111]
As title says.
YES I AM USING THE LATEST VERSION

**Comment by KulaGGin** [comment]
I see. I looked into this and found that there was an error for one of the in-game addresses. I fixed it and created a new release:
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.3

Try it out and see if it works.

**Comment by Shayoden** [comment]
Yes, now everything works perfectly.
Thank very much!

**Comment by Shayoden** [comment]
Nope, sometimes, rarely, happens again :(

**Comment by ParkourGrip** [comment]
I would check if some external programs are messing with the overlay. Other overlay programs like OBS, discord overlay, steam overlay, overwolf. No idea, it could be anything. I had no problems with OBS and Steam overlay. The rest i have no idea.

**Comment by KulaGGin** [comment]
Try newest release.
