### ISSUE TITLE
"Fight" message when starting a match. 

### ISSUE THREAD

**Issue by deathrow77** [TekkenOverlay/TekkenOverlay#113]
Hello! My issue is that the Fight message when starting a fight comes really quick (before the voice announcer says FIGHT) and it is quite confusing and annoying, is there any fix to that so the voice announcer and the message can be matched? Thanks in advance.

**Comment by ParkourGrip** [comment]
Duplicate of: https://github.com/TekkenOverlay/TekkenOverlay/issues/62
