### ISSUE TITLE
how to get frame advantage

### ISSUE THREAD

**Issue by Hyundai0** [TekkenOverlay/TekkenOverlay#114]
Hello, I'm a student who wants to study programming with Tekken 7 before Tekken 8 comes out. I had a question about frame advantage before, but I didn't understand it well, so I want to ask again. I'm curious about what memory values ​​to calculate to get the frame advantage value. I was so curious that I tried to find a way, but I can't find a way with my knowledge and skills. Please give me an answer.

**Comment by Hyundai0** [comment]
To calculate the frame advantage value, you need to perform mathematical operations on different memory values, but I'm not sure which memory values to add, multiply, or divide. Can you give me a hint or tell me how to figure out which values to use?

**Comment by ParkourGrip** [comment]
frameAdvantage = (defender.totalFramesInAnimation - defender.currentFrameInAnimation) - (attacker.totalFramesInAnimation - attacker.currentFrameInAnimation)
