### ISSUE TITLE
Broken customs and presets

### ISSUE THREAD

**Issue by Msintrax** [TekkenOverlay/TekkenOverlay#117]
New update seems to have a bug with the customs, doesn't matter which you choose (even a newly created one) the char will always have his default on. (but that's only visual) testing with my friend, he was still seeing my custom.
***edit, it seems that the presets are bugged as well, but this time will also break the game, making it stuck on a infinite load.
although... if possible, that would be a sick feature to have, to show only the default custom of our opponents
i am simply tired of those goofy and troll customs that we see on ranked haha

**Comment by KulaGGin** [comment]
Yes, it's a bug in a Character Picker feature. I created new release and disabled all new features by default. Now the Character Picker has the disclaimer about this bug.

**Comment by Msintrax** [comment]
cool, i just tested.
but i think i found another bug haha... 
i have a 1440p display, but i play at 720p... i only change it when i am watching replays
the overlay is applying the video mode settings, without our confirmation (just by hitting F1) if the resolutions don't match
