### ISSUE TITLE
Hitlines might not be accurate

### ISSUE THREAD

**Issue by compsyguy** [TekkenOverlay/TekkenOverlay#12]
![image](https://user-images.githubusercontent.com/24656119/96937729-ae241580-147d-11eb-9fb1-bb8d85555512.png)
This is Nina's b+2 - a homing move since Season 3, but the hit line doesn't go to her left at all.

There might be something else that has homing hit lines, but other homing moves look like they have hitlines that go far enough.

**Comment by JackMcCallum** [comment]
Homing moves make the character rotate to the target, they are accurate.
