### ISSUE TITLE
Crashes as soon as game is hooked, tried everything suggested in FAQ.

### ISSUE THREAD

**Issue by itdoesntmatterwhoiam** [TekkenOverlay/TekkenOverlay#120]
I just want to increase my framerate.

**Comment by kjsunday** [comment]
Same issue with me but mostly when I play rank. I literally have 0 crashes on quick but when it comes to rank after loading the match the game crashes. With the new update I takes longer to load the overlay.

**Comment by kincho21** [comment]
> Same issue with me but mostly when I play rank. I literally have 0 crashes on quick but when it comes to rank after loading the match the game crashes. With the new update I takes longer to load the overlay.

I'm also experiencing this. I can play quick matches no problem but I soon as I get into ranked the game crashes. Also experiencing crashes when opening the menu in training mode sometimes.

**Comment by Crowmeir** [comment]
Experiencing this also, the only thing I have turned on is fps unlock. It crashes on the practice mode menu most of the time.

**Comment by AndrewZ987** [comment]
Same issue here, I am using the previous version (5.10.1) and it is working fine for me, so I think you can you use that as a temporary substitute.

**Comment by kjsunday** [comment]
Just updated my Nvidia Drivers to the latest and doesn't crash anymore except when I'm playing rank. No slow loading of overlay after updating drivers.

**Comment by UrsoManso** [comment]
Is the Overlay still crashing on ranked?

**Comment by KulaGGin** [comment]
Try the newest version of the Overlay.
