### ISSUE TITLE
Title crashes immediately after the first round when setting up the FPS counter to higher than 60 

### ISSUE THREAD

**Issue by papiezyk** [TekkenOverlay/TekkenOverlay#122]
Hi, My game crashes every single time after landing the final hit in the round, it occurs on every single FPS setting. 

Current Tekken Overlay CL - TekkenOverlay-5.11.6-.2023-06-14
Current Tekken CL - Patch 5.10

Steps to repro:
1. Launch Tekken
2. Launch the Tekken Overlay in ~mods folder
3. Set the FPS counter to higher than 60
4. Play any match
5. Progress till the end of the round
6. Observe the issue

Every single setting in the Overlay is set to off except the FPS setting, enabling nametag features on/off does not change a thing sadly. I'm attaching my DxDiag config files in the ticket
[DxDiag.txt](https://github.com/TekkenOverlay/TekkenOverlay/files/11768688/DxDiag.txt)

Thank you in advance!

**Comment by KulaGGin** [comment]
Fixed in the latest release: https://github.com/TekkenOverlay/TekkenOverlay/releases/latest

**Comment by papiezyk** [comment]
holy crap, that was fast! thank you sooo much! <3
