### ISSUE TITLE
Sequencial Moves on Repeating Move List doesn't work properly

### ISSUE THREAD

**Issue by felonyf0x** [TekkenOverlay/TekkenOverlay#126]
https://youtu.be/pbGMQxJQRio

**Comment by Nights87** [comment]
I'm seeing this same issue. I would love if you could get this to work correctly!

**Comment by KulaGGin** [comment]
Yes, it's a known bug. The feature would have to be rewritten to fix this. Maybe in Tekken 8 at one point I'll do it.
