### ISSUE TITLE
**Suggestion** Adding a option to edit the Punish Training...

### ISSUE THREAD

**Issue by felonyf0x** [TekkenOverlay/TekkenOverlay#127]
Punish Training Custom...

Add a tab in TEKKEN Overlay where I can edit the Punish Training and insert custom punishes via recording, but not for Punish Training... For exemple, when I perform a Dodge against my opponent string (be it by ducking or side-stepping) the success sound is triggered. There could be insert more mechanics then dodge or punish to encourage the player to exercise and improve,

**Comment by KulaGGin** [comment]
Thanks for the suggestion. Noted.
