### ISSUE TITLE
Game crashes when injecting the game overlay

### ISSUE THREAD

**Issue by trippertje** [TekkenOverlay/TekkenOverlay#129]
whenever i start the tekken overlay when the game is already started it crashes every time.
the only way i can use the tekken overlay is when i start the overlay than start up tekken, but the game will take at least 5 minutes to start up.

**Comment by KulaGGin** [comment]
The game taking 5 minutes to start or overlay taking 5 minutes to inject is a video driver problem that people reported a while ago. Update your driver or downgrade it and then it'll just might start correctly.
