### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by fuhuan416** [TekkenOverlay/TekkenOverlay#131]
TEKKEN8 CBT, game popup Fatal error dialog when i launched game from Steam with v5.11.10.

**Comment by lamovnik** [comment]
Seems to be related to RTSS and other 3rd party (monitoring) SW.

**Comment by fuhuan416** [comment]
> Seems to be related to RTSS and other 3rd party (monitoring) SW.

Sorry that's my descripiton phault, The Fatal Error dialog is from Game isn't from TekkenOverlay.
So i'm sure don't running any RTSS or 3rd party monitorning SW.
By the way i use TekkenOverlay on Offline mod for CBT, i thought v5.11.10 is designed for Offline right? Because online is down now.

**Comment by lamovnik** [comment]
Yeah.. I had it running once (at 120 fps), but the moment I enabled RTSS, it crashed and continue to be crashing ever since. So that's where my assumption comes from.

**Comment by KulaGGin** [comment]
Not relevant anymore. New version of the game and the overlay is out.

**Comment by lamovnik** [comment]
Awesome!

**Comment by fuhuan416** [comment]
Yeah i use the newer version and it's awesome work on 1.01.03, thank you.
