### ISSUE TITLE
crashing only in rank after loading screen (when about to battle)

### ISSUE THREAD

**Issue by AdoAlexAdo** [TekkenOverlay/TekkenOverlay#133]
i genuinely have no idea why overlay is crashing when i'm gonna rank, i'm not even using it for frame cheats/name-tag but ONLY for 144 fps unlock. overlay works completely fine and I never crashed even once after using it for about 1 month IN player matches, my first game in rank crashed near end of loading screen but i didn't mind because i thought it was a bug or something, so i tried again and crashed again. im using the latest overlay and i don't really know whats the issue here. please fix

**Comment by KulaGGin** [comment]
Try the new version.
