### ISSUE TITLE
New version with Demo compatibility on the way ?

### ISSUE THREAD

**Issue by brad86m** [TekkenOverlay/TekkenOverlay#134]
I missed out on the test versions, but I am enjoying the demo now. Is there an update coming to have this working with the demo ?

**Comment by lay1550** [comment]
Was wondering as well. It crashes  even with Goldberg and manually injecting the DLL.

**Comment by brad86m** [comment]
Indeed. I'm interested in latency reduction, as even with optimized gsync settings, exclusive fullscreen, and Ultra Latency set in Nvidia control panel, there is still more input lag than on my PS5 demo.

**Comment by KulaGGin** [comment]
Updated.
