### ISSUE TITLE
wait update for season4 

### ISSUE THREAD

**Issue by baolilike** [TekkenOverlay/TekkenOverlay#15]
thk

**Comment by compsyguy** [comment]
If you're looking for memory addresses, maybe some can be lifted from here:
https://github.com/WAZAAAAA0/TekkenBot/blob/0.19.0/TekkenData/memory_address.ini

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.00.1
