### ISSUE TITLE
Failed to load game memory configuration

### ISSUE THREAD

**Issue by senseirain** [TekkenOverlay/TekkenOverlay#16]
Failed to load game memory configuration,.. how do u fix it?
Image > https://i.postimg.cc/6qxwDm40/1.jpg

**Comment by KulaGGin** [comment]
Doesn't work on season 4 for now. We will soon release a version for seaon 4.

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.00.1
