### ISSUE TITLE
I can't Tekken. Why? 

### ISSUE THREAD

**Issue by yup-yup** [TekkenOverlay/TekkenOverlay#17]
Guys please! I beg you! I donated my last 5 Euros and you no update? How come? I can't juggle. My family laughs at me Tekken. I want Tekken God Omega so I can invited in Tekken World tour and beat Arslan. Wife angry. Kids hungry. I start drinking. I tried no nut but Kunimitsu come and I don't inject soft ware. Why Kunimitsu strong? I don't know. I see no lines, no code, only screen. I'm sad. How come? What do? Please help

**Comment by baolilike** [comment]
lol u need superpower like flash u can see all enemy attack for  punish.

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.00.1
