### ISSUE TITLE
4.0.1 Not displaying frame data

### ISSUE THREAD

**Issue by JustinHit** [TekkenOverlay/TekkenOverlay#18]
![20201114175439_1](https://user-images.githubusercontent.com/6857794/99159544-d7ae1680-26a2-11eb-8853-66ffaea9af52.jpg)

I have everything as default, such as frame data as enabled.
I think it's due to this game memory being red. Changed my resolution and to boarderless but still have the same issue.
Everything else is working such as throw data and frame unlocker. Just the Frame Numbers and Hit Boxes are not.
Thanks for helping!

**Comment by WAZAAAAA0** [comment]
on 4.00 I get your same issue when I set Rendering Scale to anything lower than 100%
on 3.33, on sub-100 settings the hitboxes simply looked "different", now they don't show at all

...so try setting it to 100 <https://github.com/TekkenOverlay/TekkenOverlay#rendering-scale-issue>

**Comment by JustinHit** [comment]
You are right, thanks so much!!!!
