### ISSUE TITLE
[T7] Crashes on startup

### ISSUE THREAD

**Issue by Lunarx512** [TekkenOverlay/TekkenOverlay#182]
It just crashed back to desktop whenever i start Overlay before&after opening the game. It found process PID, Opening Process and Injecting DLL successfully then turn back to "Searching for Process ID... Not found!" and "Lost process handle!" as the game exit back to desktop without going near the Logo intro

**Comment by Lunarx512** [comment]
And i tried all the other possible fixes recommended here but none worked out yet. "Hello world DLL" works as that mean my computer can inject DLL but then, for the main game it couldn't go near the main menu unless i open the game first.

**Comment by xNadeemx** [comment]
Try https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.11.8

This was the last official T7 standalone overlay before 8 came out. I still use this one exclusively when playing T7. It may start up with the game for you.

**Comment by Lunarx512** [comment]
Thanks for the reply. But i think i already found the solution, the same way your suggestion works too. It's to try the older versions of the Overlay to see what work, my is https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.0

Anything beyond that doesn't work and just crashed/exit the game so again, thank you for this <3
P/S: Works the same way with TekkenMovesetExtractor too, older version work with older versions 👍
