### ISSUE TITLE
Floating Frame data not showing

### ISSUE THREAD

**Issue by senseirain** [TekkenOverlay/TekkenOverlay#19]
Frame data  not showing?,..
 Grab Tech works fine...
(Hitbox not showing as wel)
How do you fix this?
Video > https://streamable.com/gscw8b

**Comment by ParkourGrip** [comment]
Check that the render scale is 100%. Restore the frame data settings to default. Check that the frame-data color is not transparent in the settings.

**Comment by senseirain** [comment]
Thanks it worked,.. It seems That Tekken rendering scale was set to 75%,..
