### ISSUE TITLE
Do you have overlay for current version without font-size changer?

### ISSUE THREAD

**Issue by jo100s** [TekkenOverlay/TekkenOverlay#190]
UE-Polaris game crash occurred. I experienced this error when I used font size changer before eddy update, but now it occurs everytime right after cinematic. Hopefully a version without font size changer can solve the problem?

**Comment by wiaalwial** [comment]
Having same problem. But following this https://github.com/TekkenOverlay/TekkenOverlay/issues/169 thread, the released version wouldn't contain the font size change feature. (More accurately, disabled as default.)

But the symptom of the error looks exactly same. Even copying and pasting the file "Tekken8OverlaySetting.yaml" doesn't work too.....

Maybe the cause of the error is different at this time, or maybe the font size feature is enabled as default and KulaGGin missed that, but if it is, then "Tekken8OverlaySetting.yaml" should have solved the problem. I curious what's happening....

**Comment by jo100s** [comment]
Anyway, this tekken overlay is a gift for users. I hope I can play with 200 fps at newer version
