### ISSUE TITLE
When will the new patch be supported?

### ISSUE THREAD

**Issue by Vinchik0** [TekkenOverlay/TekkenOverlay#194]
I downloaded the program, but I can't run it because the latest version of Tekken is not supported. But the DLL Injection is fine, maybe I can use it in its current version, even if some framedate is incorrect? If not, when is the update planned?

**Comment by rllanger** [comment]
update to support 1.04 version pplease 🙏

**Comment by CCauldron** [comment]
Arghhhhhhhh save us KulaGGin

**Comment by Byorin** [comment]
Hopefully it's sooner than later.

**Comment by Joel-Hjerten** [comment]
My eyes are bleeding at 60fps.

**Comment by corgiix3** [comment]
how long does it usually take to update?

**Comment by PasswordInspector** [comment]
> how long does it usually take to update?

3 days

**Comment by troco72** [comment]
I thought I was the only one super bummed to not have this mod active

**Comment by weizhen199** [comment]
:（  I couldn't use paypal to dontate in my region. Hope there would have a patreon.

**Comment by troco72** [comment]
> :（ I couldn't use paypal to dontate in my region. Hope there would have a patreon.

You can donate via PayPal?  Mind telling me how? I've always struggled navigating github

**Comment by ex1tsense** [comment]
> > :（ I couldn't use paypal to dontate in my region. Hope there would have a patreon.
> 
> You can donate via PayPal? Mind telling me how? I've always struggled navigating github

Yes the paypal donate button is on the bottom of the readme 

https://github.com/TekkenOverlay/TekkenOverlay

scroll all the way down here

**Comment by Joel-Hjerten** [comment]
I just donated 10eur.

**Comment by Byorin** [comment]
So uh, any updates?

**Comment by OGGOATT** [comment]
@KulaGGin RELEASE THE UPDATE ASAP PLEASE !!!!!

**Comment by vicbodee** [comment]
Kinda need an update of some sort. Thanks in advance @KulaGGin

**Comment by wiaalwial** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/7.5.11-8.1.04.00-0

Finally!! Thank you KulaGGin ^.^
