### ISSUE TITLE
Feature suggestion. Hide one character's hurtboxes.

### ISSUE THREAD

**Issue by Armanlex** [TekkenOverlay/TekkenOverlay#2]
Basically the problem is when one character attacks another sometimes the attacker's hurtboxes obstruct the view and makes it hard to tell what exactly is happening between the attack lines and the defender's shapes. I'd love the ability to toggle the hurtboxes of one character to make things easier to see.

I do suspect though that it might be very difficult to do. :/

**Comment by TekkenOverlay** [comment]
Ive seen the way some people are using it and i agree, i think this feature would be handy.

We'll look into it. Thanks!

**Comment by ParkourGrip** [comment]
Feature added in version: 4.00.1
