### ISSUE TITLE
.

### ISSUE THREAD

**Issue by brad86m** [TekkenOverlay/TekkenOverlay#219]
.

**Comment by faileon** [comment]
Where exactly is the source code? This repo is just the wiki and built releases. The nitty gritty is not open sourced.

**Comment by SpiritOfSunz** [comment]
> Where exactly is the source code? This repo is just the wiki and built releases. The nitty gritty is not open sourced.

i think some one said it was in the tekken 7 fps patcher  (im not a coder or anything so idk but heres the link https://github.com/KulaGGin/Tekken-7-FPS-Patcher)

**Comment by haziqtheunique** [comment]
Communication is important with any project, even if it's just communicating with the people who use your thing. Hell, ESPECIALLY if that's the case.

If the dev has things going on in his life, that's fine. But it would be great if he would communicate that. It would be even better if he could branch this off or invite more devs so that others can help out, if he's unable or unwilling to work on it for whatever reason. It's the radio silence for multiple patches now that has people concerned.

**Comment by brad86m** [comment]
> Communication is important with any project, even if it's just communicating with the people who use your thing. Hell, ESPECIALLY if that's the case.
> 
> If the dev has things going on in his life, that's fine. But it would be great if he would communicate that. It would be even better if he could branch this off or invite more devs so that others can help out, if he's unable or unwilling to work on it for whatever reason. It's the radio silence for multiple patches now that has people concerned.

He owes us nothing. This is a little project he's obviously doing in his free time for no cost. 
I was wrong in my assumption that the source code is there. Turns out only the case for T7. That being said, nothing should be stopping anyone else from creating a similar mod/tweak. But, it's obvious at this point that laziness and expecting others to do everything is what stops people from doing so.

**Comment by wiaalwial** [comment]
Hmm.... Then what stops you from continuing the project? You woudn't admit that is your laziness.

If you have a good reason than your laziness, then what makes you judge rashly that other people don't have the same reason with you?

**Comment by hg1217** [comment]
I would literally do that if I wasn't bad at programming

**Comment by brad86m** [comment]
> Hmm.... Then what stops you from continuing the project? You woudn't admit that is your laziness.
> 
> If you have a good reason than your laziness, then what makes you judge rashly that other people don't have the same reason with you?

Nothing, that's why I have done my own stripped down version for the current T8 patch. It's essentially identical to T7 code. Only with each new patch, hex values need to be changed.

**Comment by hg1217** [comment]
Could you please upload to a public repo @brad86m

**Comment by SpiritOfSunz** [comment]
> > Hmm.... Then what stops you from continuing the project? You woudn't admit that is your laziness.
> > If you have a good reason than your laziness, then what makes you judge rashly that other people don't have the same reason with you?
> 
> Nothing, that's why I have done my own stripped down version for the current T8 patch. It's essentially identical to T7 code. Only with each new patch, hex values need to be changed.

if thats the case are you willing to share what you have done? or at least create a guide on how to do it our selves?  im not a coder and i dont know how to. im just a tekken enjoyer , in my specific case its not about laziness its just a skill diff.

**Comment by wiaalwial** [comment]
> > Hmm.... Then what stops you from continuing the project? You woudn't admit that is your laziness.
> > If you have a good reason than your laziness, then what makes you judge rashly that other people don't have the same reason with you?
> 
> Nothing, that's why I have done my own stripped down version for the current T8 patch. It's essentially identical to T7 code. Only with each new patch, hex values need to be changed.

If you were trying to make your own version, you would have find the source code. Meanwhile, until just three days ago, you've no idea about that the source code of Overlay for T8 is not released. I wonder why.

Just a question. Not a doubt.
