### ISSUE TITLE
Donation area issues

### ISSUE THREAD

**Issue by wlsvyh** [TekkenOverlay/TekkenOverlay#24]
I want to donate, but I cannot make a donation with a message stating, "Donation to this recipient is not supported in this country (S. Korea)”. Is there another way?

**Comment by JackMcCallum** [comment]
Maybe you can try the USD version.
[https://www.paypal.com/donate/?cmd=_donations&business=tekkenoverlay%40gmail.com&currency_code=USD](url)

If this doesnt work maybe paypal doesnt support making donations from S. Korea and we thank you for your support :)

Please let me know if this works, I will update the readme with it

**Comment by wlsvyh** [comment]
> Maybe you can try the USD version.
> [https://www.paypal.com/donate/?cmd=_donations&business=tekkenoverlay%40gmail.com&currency_code=USD](url)
> 
> If this doesnt work maybe paypal doesnt support making donations from S. Korea and we thank you for your support :)
> 
> Please let me know if this works, I will update the readme with it


I tried with the link "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=tekkenoverlay%40gmail.com&currency_code=USD", but as before, "Donation to this recipient is not supported in this country" appears and does not proceed. :( Unfortunately, if there is a way to donate, we will try again.
