### ISSUE TITLE
Feature Suggestion: Display the name of an opponent before accepting a match

### ISSUE THREAD

**Issue by Loemnk** [TekkenOverlay/TekkenOverlay#26]
While Namco removed the ability to see the names of opponents pretty early on, there is still a way to do this.

I know from playing around with Cheat Engine that you can still search for strings to display the names of Opponents before accepting a match

But since I'm a noob when it comes to this, this seems to be pretty inconsistent and will not always work.

I know people might be split on this topic, but I would love to be able to avoid playing against laggy or toxic people.

Regardless whether or not this is implemented, thank you so much for your hard work on this amazing tool!

Cheers

**Comment by ParkourGrip** [comment]
This will not be implemented since it would allow players to dodge bad match-ups.
