### ISSUE TITLE
Problems with Proton

### ISSUE THREAD

**Issue by EvgenijM86** [TekkenOverlay/TekkenOverlay#27]
When I try to launch it with Proton on Linux the following things happens:
1) If I launch it before tekken then tekken simply does not start.
2) If I launch it after tekken the tekken might freeze or not freeze after "Injecting DLL... Successful." message. Seems completely random, but it freezes a lot more than not freezing. If it does not freeze then nothing happens - the F1 menu does not pop-up when F1 is pressed and game displays the same way as if the overlay does not exist.

The version of Proton that I used is 5.0. I did install VC_redist.x64.exe. The script that I use to install VC_redist.x64.exe and to run overlay is the following:

```
#!/bin/sh

# Application path
APP_PATH="$(dirname "${BASH_SOURCE[0]}")"
cd "$APP_PATH"

# Executable file
APP_EXEC="$APP_PATH/$1"

# Steam / IDs
export SteamAppId="389730"
export SteamGameId="389730"

# Steam / Client path
export STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam"

# Steam / Apps path
STEAM_APPS_PATH="$HOME/SSD/Games/SteamLibraryLinux/steamapps"

# Steam / Compat data path
export STEAM_COMPAT_DATA_PATH="$STEAM_APPS_PATH/compatdata/$SteamAppId"

# Proton / Path
PROTON_PATH="$HOME/SSD/Games/SteamLibraryLinux/steamapps/common/Proton 5.0"

# Proton / Executable script
PROTON_EXEC="$PROTON_PATH/proton"

python "$PROTON_EXEC" run "$APP_EXEC"
```

The same setup works with TekkenBotPrime without any issues.

![image](https://user-images.githubusercontent.com/430076/99476569-b66e5400-2948-11eb-84ab-5c8e78f9b92e.png)

**Comment by ParkourGrip** [comment]
I have no idea how dll injection works in proton. You are better off making your own dll injector and inject the `tekken-overlay.dll` manually yourself.
