### ISSUE TITLE
rendering scale issue

### ISSUE THREAD

**Issue by HassoTobi** [TekkenOverlay/TekkenOverlay#28]
this probably isnt the place to ask, but is there anyway to use this overlay without setting the rendering scale to 100 ? my PC is very poor and needs this set to a lower value for the game to run at 60fps.

**Comment by koreagunba** [comment]
i have the same issue

**Comment by ParkourGrip** [comment]
Fixed in [4.10.1](https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.10.1).
