### ISSUE TITLE
Proccess ID not found

### ISSUE THREAD

**Issue by razmord** [TekkenOverlay/TekkenOverlay#29]
I have downloaded the last version, installed the VC distributables, unzip the folder (on both a regular folder and the Tekken folder just in case) and tried launching the exe before and after I open Tekken on Steam. No matter what, it always keeps showing
Searching for process ID... NOT FOUND!
over and over again. The only way I've manage to make it say that it's injecting DLL is by manually launching Tekken 7.exe on the Tekken 7 folder,  but it eventually says Lost proccess handle! without even opening the game.

I'm on Windows 10.

**Comment by vinjames006** [comment]
I am also  seeing this error message. Windows 10. I did install the C++ Redist. that matches my cpu arch.

**Comment by razmord** [comment]
It magically fixed itself, have no idea why.

**Comment by vinjames006** [comment]
Unfortunately mine is still showing this error.

**Comment by ParkourGrip** [comment]
In order for the injector to find the process, it needs to be called `TekkenGame-Win64-Shipping.exe`. If for whatever reason your process is not called that the injector will not know what process is Tekken so it dose not know in what process it needs to inject.

**Comment by Niceguy18** [comment]
I had the same problem. I ran the program as Administrator and it worked.
