### ISSUE TITLE
Frame numbers and Hitboxes not showing [Solved]

### ISSUE THREAD

**Issue by Sakelig** [TekkenOverlay/TekkenOverlay#31]
The other day they just didnt show up anymore, tried to reset default settings, redownload the overlay and everything i thought could fix it but nothing. Everything else works, throw tech, custom fps, game info.
Overlay msg is 
"Opening process... Succcessful."
"Injecnting DLL... Successful."

Dunno wat more to try to fix it, i just want to git gud fast and this tool has been amazing so far for learning.

If anyone has any ideas to try out to fix it pls tell

**Comment by JackMcCallum** [comment]
Make sure your game render scale is set to 100

**Comment by Sakelig** [comment]
> Make sure your game render scale is set to 100

That did it for me! Thanks alot! Dont remember changing anything in settings. but it works now so im happy
(Just went to graphic settings and put the render scale to 100)
