### ISSUE TITLE
Frame Information Not Displayed

### ISSUE THREAD

**Issue by wi030730** [TekkenOverlay/TekkenOverlay#32]
Throw Tech is displayed, but frame information and hit box are not available

**Comment by Truuce** [comment]
same issue here. Ping and frame time also works.  In game memory > gameValues. "displayMode is red. along with everything in that field(pointer, address, bit, refreshRate)

**Comment by Truuce** [comment]
figured it out. go into settings and make sure your Rendering scale is set to 100 or more.

**Comment by ParkourGrip** [comment]
Duplicate of: #28
