### ISSUE TITLE
Error: swapChain ->GetDevice

### ISSUE THREAD

**Issue by jaymurr1** [TekkenOverlay/TekkenOverlay#34]
Haven't seen this issue anywhere else. Whenever I open the overlay, it says it injects successfully but a different error pops up instead. I have the overlay extracted and VC++ updated, so I'm not sure what's causing the issue. Opening the overlay before/after tekken itself and running it in or out of admin mode also don't make any difference.

**Comment by ParkourGrip** [comment]
Probably fixed in more recent updates?
