### ISSUE TITLE
Enhancement: Support Template Strings in Conditional Rules

### ISSUE THREAD

**Issue by paprende** [TekkenOverlay/TekkenOverlay#36]
Hi TekkenOverlay Team. 

It would be nice if there was a way to add a template string to a conditional rule. 

For example
```
{{frame_number}} : {{hit_property}}
```
would display 
```
+9 : High
```

Users could then create their own customised display values and show other properties as part of the expression

**Comment by ParkourGrip** [comment]
I don't think that's necessary.  I don't want to implement complicated animated font rendering just for some corner use-case that no one uses.
