### ISSUE TITLE
Here's a question.

### ISSUE THREAD

**Issue by hhm-h** [TekkenOverlay/TekkenOverlay#40]
Hello, developers.
Thank you so much for the patch.
What is the overlay mark next to the Steam nickname after today's patch?

**Comment by ParkourGrip** [comment]
It makes your opponents know that you are using a overlay. In order to get rid of it all you need to do is to restart the game without running the overlay.

**Comment by manishguptaji** [comment]
How to kill a software and its user base with a new thoughtless feature.
