### ISSUE TITLE
The (overlay) in your name

### ISSUE THREAD

**Issue by justatempnamefornow** [TekkenOverlay/TekkenOverlay#41]
the overlay in the name is just a great reason for people to be super toxic/mad. Is there a reason this was added? And is it possible to disable it?

**Comment by lmaok549** [comment]
This is what ParkourGrip told me hours ago.

> Working as intended. No need to hide if you are using it. No sneaky online tournament hackers allowed.

We tagged now if we use this

**Comment by ParkourGrip** [comment]
Duplicate of: #40
