### ISSUE TITLE
Exception occured: Couldn't create hook for 5375941200 function with MH_CreatehookEx. MH_STATUS is 8.

### ISSUE THREAD

**Issue by axl-parangan** [TekkenOverlay/TekkenOverlay#46]
![20210425221727_1](https://user-images.githubusercontent.com/32169524/115997201-e404ab00-a614-11eb-87b7-733ea37f8931.jpg)

Been using overlay for a long time but it's just last week I've encountered this issue, I also haven't done or installed any windows updates on my computer the error just suddenly popped up

**Comment by KulaGGin** [comment]
Yep, it needs updating for the new patch. Working on it.

**Comment by ParkourGrip** [comment]
The only thing that broke is custom FPS. As long as you disable that feature everything else still works.

**Comment by KulaGGin** [comment]
Fixed in the new release: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.11.0
