### ISSUE TITLE
not working after update 28/09/2021

### ISSUE THREAD

**Issue by kemalelele** [TekkenOverlay/TekkenOverlay#51]
overlay not working after new update, just credits appear, any idea why?

**Comment by pimment69** [comment]
It's the same for me, we need to update this, but idk if Parkourip gonna do the update very soon, we have to wait

**Comment by FimoX** [comment]
@ParkourGrip 
If that can help you, I've updated the new offsets for TekkenBotPrime:

[memory_address.zip](https://github.com/TekkenOverlay/TekkenOverlay/files/7267959/memory_address.zip)

**Comment by FimoX** [comment]
[CE_TekkenBot.zip](https://github.com/TekkenOverlay/TekkenOverlay/files/7270881/CE_TekkenBot.zip)
[memory_address.zip](https://github.com/TekkenOverlay/TekkenOverlay/files/7270882/memory_address.zip)

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.22.0
