### ISSUE TITLE
Issues on some modded maps due to interpolation

### ISSUE THREAD

**Issue by AuraOfPrimalMajesty** [TekkenOverlay/TekkenOverlay#56]
For example on DennisStanistan's Moonlit Blossom Optimized map the walls completely glitch out, if interpolation stays off until the character intro then enabled it bypasses the issue, if that was automated when enabled it would be great.
-- also im playing at 165 fps if that's relevant

**Comment by KulaGGin** [comment]
Interpolation causes a few glitches like this, yes. It also causes some character items to be enlarged to the point where the game is unplayable for that match. I never got to fixing it. To fix these problems, the feature would have to be reimplemented using a different approach. I don't know when I'm going to get to it, maybe in Tekken 8.
