### ISSUE TITLE
Practice mode, repeat action help?

### ISSUE THREAD

**Issue by callumhalo** [TekkenOverlay/TekkenOverlay#60]
Hey!

I saw that there has been some useful practice mode settings made on the overlay like restart settings etc.

I saw there was a repeat action column that could be used to add perhaps more than 5 moves for repeat action, but I'm unsure how to get it working?

Move ids? how do you start it?

I think it could be awesome practicing vs more than 5 moves at a time.

**Comment by KulaGGin** [comment]
Like this:
https://user-images.githubusercontent.com/16989713/149812080-c95ae629-a9ba-4530-bc1a-85cf11a6cb91.mp4

Select Repeat Action 1 as movelist, choose moves, press Add button in the overlay, then choose any move from the list inside the game and press play to start playing different moves.

**Comment by callumhalo** [comment]
Hey, thanks!
This'll help loads! - Got it working!
I assume adding recorded actions won't interfere with the list?

Would it be possible to do something similar for recordings? (probably 20x harder to code)
I was just thinking of some strings where you'd want to finish them early perhaps!

**Comment by KulaGGin** [comment]
> Would it be possible to do something similar for recordings? (probably 20x harder to code)
> I was just thinking of some strings where you'd want to finish them early perhaps!

Added this with the latest releases.
