### ISSUE TITLE
Injecting DLL... Fail! when process started from a .bat file

### ISSUE THREAD

**Issue by goudekid** [TekkenOverlay/TekkenOverlay#61]
See title, I want a bat file that starts both tekken and the overlay simultaneously as I always forget to start it, but if I start it via a .bat file (even with run as admin) it fails to inject.

**Comment by ParkourGrip** [comment]
Tested batch script:
```
start /d "C:\path\to\tekken\overlay" tekken-overlay-run.exe
start /d "C:\path\to\TEKKEN 7\TekkenGame\Binaries\Win64" TekkenGame-Win64-Shipping.exe
```
Works fine.
