### ISSUE TITLE
the fps doesn't work

### ISSUE THREAD

**Issue by CeroYuriy** [TekkenOverlay/TekkenOverlay#63]
So I inject the dll and I don't get over 60fps anymore. I used to, but not anymore and I've no idea what the problem might be. I don't think it's anti virus either. I deleted them, and it used to work even with them..

**Comment by ParkourGrip** [comment]
Something else is probably limiting your FPS. 
Check if you have anything like v-sync, g-sync, whatever-sync enabled.
Any other applications that could limit the FPS like other overlays or Riva Tuner Statistics Server? 
Are you sure you can run the game on above 60 fps on your current settings?
Maybe you have resolution scale on 200% and that's like running the game on twice the resolution.

**Comment by CeroYuriy** [comment]
it was the v sync from nvidia control panel settings. Thx!
