### ISSUE TITLE
Display Settings, dosen't work anymore

### ISSUE THREAD

**Issue by Soyzi** [TekkenOverlay/TekkenOverlay#64]
Hello guys, i have find this amazing overlay 3 days ago, mostly for input lag online, and i've laso tried the display settings, i put my fps to 144 so i can benefit my 144hz monitor and the game was so smooth that was amazing.

I played like that for 3 days no problem, got like 2-3 crash but okay, and today after a crash i restart the game and it feel like 60hz but my game still show 144fps if i change it to 60 no difference at all 60 or 144 fps just feel the same as if tekken does not take into account my 144hz monitor, i tried another game re2 remake for example and the 144hz work fine.

The V sync in my nvidia setting is off and the steam overlay show 144fps so i dont know, i've also format my pc today because he was running slow those days and the problem is still here.

Someone know what the problem could be ? 

Sorry for my english.

**Comment by ParkourGrip** [comment]
The game updated today. Memory addresses changed for a bunch of stuff. You are going to have to wait for us to update the overlay. Give us a week.

**Comment by Soyzi** [comment]
Oh ok.
Thanks for the reply and the amazing job on this overlay.

**Comment by Zipmasterflexx** [comment]
Thanks alot for that post. did anyone also notice that the game crashes when you break a balcony? has anyone alse had this happen? when i run the overlay the always! crashes as soon as i break a balcony.

**Comment by Soyzi** [comment]
that was fast, thanks for the update, appreciate it.


> Thanks alot for that post. did anyone also notice that the game crashes when you break a balcony? has anyone alse had this happen? when i run the overlay the .exe always! crashes as soon as i break a balcony. So @ParkourGrip you are already working on an update? thanks in advance, that overlay is the best mod i have ever seen for a video game ever. thank you guys so much.

Try it now maybe every thing should work

**Comment by ParkourGrip** [comment]
Fixed here: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.27.0 Closing the issue.
