### ISSUE TITLE
Interpolation bug on Devils Pit

### ISSUE THREAD

**Issue by shinzo8** [TekkenOverlay/TekkenOverlay#66]
Tried this with 0 mods as well, I got to reproduce it consistently. 
Just get in game into devils pit, and hit the check for interpolation or have it enabled before loading in, issue goes away right away with no restart if you uncheck interpolation. Haven't checked all maps yet.

https://user-images.githubusercontent.com/99839456/154351028-cfdf5473-0784-4dab-ae04-478c5ab6ad78.mp4

**Comment by ParkourGrip** [comment]
Probably related: https://clips.twitch.tv/LongLivelyAmazonHeyGuys--M9AA0MJ8SmpY3fW

**Comment by KulaGGin** [comment]
Thanks for reporting. I could reproduce this and fixed in the newest released: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.27.1
