### ISSUE TITLE
Game crashes in certain scenarios

### ISSUE THREAD

**Issue by zedokker** [TekkenOverlay/TekkenOverlay#67]
1.
If I start overlay and then Tekken7, Tekken7 will crash if I go back to the main menu or the map reloads.
If I start Tekken7 and then overlay, Tekken7 will not crash.

2.
Tekken7 crashes with overlay running if a character gets wall splatted at a certain angle. Currently tested on Mishima Dojo
with Akuma. Custom FOV and custom FPS is enabled.

**Comment by KulaGGin** [comment]
> 1.
> If I start overlay and then Tekken7, Tekken7 will crash if I go back to the main menu or the map reloads.

From what game mode? Practice mode? Player Match - Lobby? Some other game modes?

I couldn't reproduce your error on any recent versions of the overlay. On what version of the overlay you got this error? You can see the version at the bottom of the screen.

Try newer version of the overlay: https://github.com/TekkenOverlay/TekkenOverlay/releases/latest and see if it still happens on the newer version of the game.
