### ISSUE TITLE
Tekken Crashes When Trying to use Record Moves/Inputs

### ISSUE THREAD

**Issue by manav907** [TekkenOverlay/TekkenOverlay#68]
After using the tekken overlay's repete action every time i try use record move inside tekken the game crashes consistanly. the only fix is to not use overlay at all. i have tried openeing overlay before the game starts, after the game starts, complete redownload of tekken overlay.

**Comment by KulaGGin** [comment]
Try newer release: https://github.com/TekkenOverlay/TekkenOverlay/releases/latest

**Comment by anadarjn** [comment]
Hello. I tried the latest version and the side wall crash doesn't seem to happen which is good.
Going back into the main menu from Practice and online waiting lobby does not result in a crash, also good.

But when starting the overlay mod first the game will crash when going back to waiting room/lobby.
Terminal:
Opening process... Successful.
Injecting DLL... Successful.
Lost process handle!
Searching for process ID... NOT FOUND!

However this issue does not happen if I start the game first and then the overlay program.

**Comment by ParkourGrip** [comment]
I'm going to assume that the update fixed the problem.
