### ISSUE TITLE
Remove Watermark

### ISSUE THREAD

**Issue by Flowrif** [TekkenOverlay/TekkenOverlay#69]
Hi love your mod! How do I remove watermark at the bottom of screen? I am a streamer.

**Comment by ParkourGrip** [comment]
You can disable "Capture third-party overlays (such as steam)" in your OBS settings:
![image](https://user-images.githubusercontent.com/1338621/156427135-cef7bd66-c017-48a1-8714-89b30ebd4def.png)
After this the watermark is not going to appear on your stream.

**Comment by Flowrif** [comment]
TY!  That works ,but I really wanna have the option to remove it altogether! 😄
