### ISSUE TITLE
Detect if the user is playing ranked and disable the overlay

### ISSUE THREAD

**Issue by ejrichards** [TekkenOverlay/TekkenOverlay#7]
In an effort to stop the overlay being used as a cheat, would it be possible to detect if the user is playing in ranked and disable the overlay?

**Comment by vissegard** [comment]
whats even the point, people were using TekkenBotPrime online anyways...

**Comment by JackMcCallum** [comment]
Since community feedback seems rather positive at this stage its unlikely this will happen.

Im not sure if its even possible at this stage.
We dont exactly have the source code of the game just lying around.

**Comment by misterperson** [comment]
In the Game Data section of the overlay options, there is a flag set for when the game thinks its in Single Player (offline). May be possible. But adding a check to disable the overlay could itself be disabled by a modification to the executable

**Comment by DennisStanistan** [comment]
> Since community feedback seems rather positive at this stage its unlikely this will happen.
> 
> **Im not sure if its even possible at this stage.**
> **We dont exactly have the source code of the game just lying around.**

It's possible to tell if the player is in an online match by hooking SteamAPI and getting the current lobby id if it exists or you can find a boolean in memory that is set to 1 when a player is playing a match and there is also an array of online players that you can access. If the second player's name string is not null then the player is likely in an online match (TekkenBotPrime has that array pointer, it just needs to be updated).

Alternatively you can get the game mode value (0x21/0x22 = Practice mode, 0x3/0x4 = On going match irrc, KulaGGin knows about this one as well) and restrict the overlay to only appear when the game mode value is set to 0x21.

off topic: This is why making this project open source will be great as other members can add and update improvements like these with ease and create a pull request

**Comment by ParkourGrip** [comment]
I guess the name changer feature fixed this problem. I'll close this issue.
