### ISSUE TITLE
[Feature Request] Enable CPU opponent in practice, but with specific move weighted higher for usage

### ISSUE THREAD

**Issue by goudekid** [TekkenOverlay/TekkenOverlay#70]
This might be totally out of scope for TekkenOverlay, but with the already implemented improvements to practice mode and the fact that you seem to know your way around the game's internals pretty well I figure I might as well ask; 

I would really love the ability to set one or more moves on the practice dummy, and then set it to CPU play, and have it play as it normally would, except with a larger bias/weighting for using the moves I set. It's one thing to practice just the moves in isolation, but it's an entirely different beast to actually deal with them even semi-organically, with movement, many other moves, etc. 

For instance, I can fuzzy Asuka's snakeedge mixup pretty reliably on it's own, and even with other moves mixed in as other actions, but I still eat it way more than I would like in real matches. It would be great to fight a CPU that essentially spams these moves, but not exclusively, if you get me.

**Comment by KulaGGin** [comment]
Try the newest release, it allows you to add random movement into the mix.
