### ISSUE TITLE
Hide 'Tekken Overlay' text at bottom of screen

### ISSUE THREAD

**Issue by CharlieM1997** [TekkenOverlay/TekkenOverlay#72]
I'm only interested in the FPS feature, which was integrated into Tekken Overlay. The text at the bottom of the screen is extremely distracting when playing. I'd appreciate a way to turn it off.

**Comment by UltraKingCombo** [comment]
Same here, looks terrible!

**Comment by WAZAAAAA0** [comment]
Just replace the relevant text with spaces using any hex editor yourself.
in `tekken-overlay.dll` search for:
`25 73 20 76 25 73 20 5B 25 73 5D`
replace with:
`20 20 20 20 20 20 20 20 20 20 20`

or download this with the change pre-applied to the current version [TekkenOverlay-5.00.1-.2022-08-20NULLED.zip](https://github.com/TekkenOverlay/TekkenOverlay/files/9439826/TekkenOverlay-5.00.1-.2022-08-20NULLED.zip)
