### ISSUE TITLE
Game crashes with newest update

### ISSUE THREAD

**Issue by envoycookie** [TekkenOverlay/TekkenOverlay#73]
Opening the overlay makes the game crash to desktop. Patch was pretty tiny probably was probably for this and other third party programs.

**Comment by discopipilu** [comment]
> Opening the overlay makes the game crash to desktop. Patch was pretty tiny probably was probably for this and other third party programs.

I had the same problem

**Comment by ParkourGrip** [comment]
Fixed in: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.28.0
