### ISSUE TITLE
Game Crashing on Online Match Start

### ISSUE THREAD

**Issue by tskibitzki** [TekkenOverlay/TekkenOverlay#74]
Extrapolation is set to 0 when it crashes, and it doesnt crash on 1. probably a divide by 0 somewhere?

**Comment by ParkourGrip** [comment]
Can you post what version of the overlay you are using? Just to be sure you are using the latest one that's compatible with yesterday's patch.

**Comment by KulaGGin** [comment]
Can't reproduce here. Record a video of what you do and in what order, so we can try and reproduce the problem.

**Comment by ParkourGrip** [comment]
I just tested it on 3 different online opponents. No crashes.

**Comment by tskibitzki** [comment]
Idk if u can see this reply but im at work ill try to recreate on my lunch
break

**Comment by tskibitzki** [comment]
I found it is unrelated to the overlay.

for some reason my game now crashes when playing/fighting Jin. I fought 2 in a row, causing my two crashes that I attributed to the overlay, I changed the extrapolation after this crash and also got paired against someone not playing Jin. 

My bad, thanks for the quick replys
