### ISSUE TITLE
Maven parry issue.

### ISSUE THREAD

**Issue by adramales** [TekkenOverlay/TekkenOverlay#77]
When Maven parry occures in match it causes all overlay users to have their game crashed.
Have only tested with 144 fps, quaternion interpolation.

**Comment by Pyrok1nezyz** [comment]
same shit +

**Comment by ParkourGrip** [comment]
Fixed in: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.28.1

**Comment by ParkourGrip** [comment]
I still saw some crashes online vs Master Raven on other people's stream and I am unable to figure out what move is causing it.
We tried to test every MR parry move online but it did not want to crash for us when we wanted to reproduce it.

**Comment by ParkourGrip** [comment]
Hopefully the random crashing is fixed in the latest patch: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.28.2
Hopefully.
