### ISSUE TITLE
Restart Manager Should Include Z Axis and Rotation

### ISSUE THREAD

**Issue by PickleTicklewithnospace** [TekkenOverlay/TekkenOverlay#81]
If I set a position, then reload the game, the Z position (height) where the character is standing on multi-floor stages will be incorrect and there is no way for the user to set this value.

e.g. Howard estate -> Break all walls -> Remember current position as restart -> Restart (restart works fine) -> Reload game -> Restart (now I'm under the floor)

Setting the rotation of both characters would be extremely useful as well. Currently in game, each player has a `Player Direction`: Front/Back/Left/Right, but setting a number value in degrees would make this more useful.

**Comment by KulaGGin** [comment]
> Currently in game, each player has a Player Direction: Front/Back/Left/Right, but setting a number value in degrees would make this more useful.

Added value in degrees in latest releases.

> e.g. Howard estate -> Break all walls -> Remember current position as restart -> Restart (restart works fine) -> Reload game -> Restart (now I'm under the floor)

This should be fixed in the latest releases, too.

You can reopen the issue if you still getting the problem.
