### ISSUE TITLE
Is the Overlay autostart?

### ISSUE THREAD

**Issue by UltraKingCombo** [TekkenOverlay/TekkenOverlay#82]
I just interessted in the 120fps mod.
I can start and use it with the overlay.
But is there any way that i dont need to start the overlay Programm everytime again if i want to use Tekken 7 in 120fps?

I read there is a 120fps Patcher but i dont know how that works, and dont find any Guid on Internet.

Or i do Something wrong?

**Comment by ParkourGrip** [comment]
There is something about it over here: https://raw.githubusercontent.com/TekkenOverlay/TekkenOverlay/master/wiki/videos/Making%20the%20game%20automatically%20load%20the%20overlay%20on%20the%20game%20start.mp4
