### ISSUE TITLE
Frame advantage on whiff wrong for moves with different recovery on hit/block

### ISSUE THREAD

**Issue by RogerDodger** [TekkenOverlay/TekkenOverlay#83]
Title

Example of some such moves:

* Claudio uf+4 (Overlay says -29, actually -36)
* Lee 4,4 (Overlay says -24, actually -29)
* Leo df+2+3 (Overlay says -26, actually -30)
* Lidia HAE.1+2 (Overlay says -26, actually -29)
* Lidia 3,2 (Overlay says -20, actually -24)
* Lidia uf+4 (Overlay says -30, actually -32; this one also has 34 frames recovery on block)
* Jin f,n,d,df#2 (Overlay says -24, actually -27)

The number the overlay gives is accurate but only for the recovery on hit/block (except with Lidia's uf+4).

**Comment by KulaGGin** [comment]
See #13.
