### ISSUE TITLE
**Suggestion** Adding Recovery Animation in Frame History bar

### ISSUE THREAD

**Issue by Shayoden** [TekkenOverlay/TekkenOverlay#84]
Hi, I would like to propose the implementation of an option that get your frames in the Frame History bar colored in light blue when you are under the recovery animation.
This would be useful to understand where you are wrong in timing when doing high execution stuff, like the juggle with Jin with F4 ch without stance: let's assume that I cannot begin to run after hitting with that move. How many frames am I pressing the second F to begin to run before the recovery animation ends? With this, I could know.
Same would be useful with the microdash in the 100$ combo, or with difficult juggles like Nina's or Lee's, to see where you are wrong with timings.

**Comment by ParkourGrip** [comment]
I'm pretty sure that this is already encoded into "Show Cancel Window" feature.
That particular feature was copied from Tekken Bot Prime so I'm not sure what exactly each color represents.
However I'm pretty sure when the squares are red you are unable to do anything (your character is blue in practice mode).
