### ISSUE TITLE
Crashes often

### ISSUE THREAD

**Issue by Shayoden** [TekkenOverlay/TekkenOverlay#86]
Crashes almost everytime you open Simple Select in pratice mode

**Comment by Shayoden** [comment]
and when you open the menu

**Comment by KulaGGin** [comment]
What version of the Overlay are you using? You can find it at the bottom of the screen after it starts.

**Comment by Shayoden** [comment]
I am using the last, 20 august.
I am constantly checking the update page to check if a new version without this problem is released.

**Comment by Shayoden** [comment]
Even uninstall and reinstall the game: it crashes anyway.

**Comment by KulaGGin** [comment]
Old stale issue. Feel free to open a new one if you're still getting crashes and problems.
