### ISSUE TITLE
There should be more description on colour meanings of the cancel window in frame data

### ISSUE THREAD

**Issue by PickleTicklewithnospace** [TekkenOverlay/TekkenOverlay#87]
The terminology used should be clarified in the menu, especially between attack state and cancel window. This was honestly a huge pain to figure out

Attack State
- green = player is in idle animation
- red = startup frames
- yellow = active frames (when the opponent can be hit)
- blue = "recovery" frames (all the **animation** frames after the active frames, NOT the real recovery where the player can't block [like defined here](https://wavu.wiki/t/Notation#Recovery))
 - if the player is holding back, then we get to see the _actual_ recovery frames since the animation gets cut off early
 - this honestly feels useless where the cancel window's red frames is a more accurate description of the recovery frames

Cancel window
- blue = player is in idle animation (this should be green since it's the exact same thing as attack state's green)
- red = start up frames before and after the active frames where player can't block or do anything (also the recovery window where player can't block on whiff)
- pink = cancellable window (player is finished with recovery and can cancel the rest of the move's animation with any input)

Just an aside, input buffer window would be nice to have (8 frames before the first pink frame in cancel window)

**Comment by KulaGGin** [comment]
We'll keep this in mind if we decide to work on this feature more in the future.
