### ISSUE TITLE
What Happned to TekkenOverlay Files

### ISSUE THREAD

**Issue by manav907** [TekkenOverlay/TekkenOverlay#90]
Coming back to this github after a long while because my overlay causes tekken to crash. but what has happened to all the files in the repo? where are they and how do i use tekken overlay now? . i just want to be able to use this while playing with my friends i don't care about the overlay tag.

**Comment by ParkourGrip** [comment]
You can download any version of Tekken Overlay from: https://github.com/TekkenOverlay/TekkenOverlay/releases
