### ISSUE TITLE
new tekken update broke overlay

### ISSUE THREAD

**Issue by Mohtar23** [TekkenOverlay/TekkenOverlay#98]
whenever i start online ranked the game crashes ( i just found the improve online lag crashes the game ) idk about the other options that might crash the game

**Comment by RockKenny** [comment]
same

**Comment by Flowrif** [comment]
thanks 4 this much info. Now I know what to disable!

**Comment by zcrx** [comment]
I've no doubt my mans already on it as we speak. Gonna donate next pay day again to show love.

**Comment by Mackzim** [comment]
Don't worry, 

I'm sure he's working on an update already. Usually took him about 3-5 days in the past.

**Comment by RockKenny** [comment]
THX FOR UPDATE!

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.01.0
