### ISSUE TITLE
tekken crashes going into practice mode

### ISSUE THREAD

**Issue by itsuhmen** [TekkenOverlay/TekkenOverlay#99]
my tekken kept crashing using the mod everytime going into practice mode, can't seem to find a way to fix this, any help?

**Comment by AndrewZ987** [comment]
It's because the game updated so the addresses don't match anymore. The author has confirmed that he is going to update the overlay recently.

**Comment by ParkourGrip** [comment]
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.01.0
